### ISSUE TITLE
Use of placeholder with optional value in spades.wdl

### ISSUE THREAD

**Issue by jdidion** [biowdl/tasks#282]
On line 62, `singleCell` is used as a placeholder expression with `true` and `false` options. `singleCell` is type `Boolean?` but true/false options can only be used with type `Boolean`. Change to `~{true="--sc" false="" select_first([singleCell])}`. If `singleCell` is undefined, the placeholder is replaced by the empty string. This is implied a couple of places in the 1.0 spec and made explicit in 1.1.

**Comment by rhpvorderman** [comment]
Thank you for pointing this out.

A better way of doing this is indeed to use defaults. `Boolean singleCell = False`. By default that means there will be no flag, which is a sane default.
